version: '3.7'
services:
  suma:
    container_name: suma
    build:
      dockerfile: Dockerfile
      context: ./microservicios/suma
    ports:
      - '8090:8080'

  biblioteca:
    container_name: biblioteca
    build:
      dockerfile: Dockerfile
      context: ./microservicios/biblioteca
    ports:
      - '8091:8080'
  
  bibliotecatest:
    container_name: bibliotecatest
    build:
      dockerfile: Dockerfile.test
      context: ./microservicios/test
      
  sumatest:
    container_name: sumatest
    build:
      dockerfile: Dockerfile.test
      context: ./microservicios/suma

  sitioweb:
    container_name: sitioweb
    build:
      dockerfile: Dockerfile
      context: ./sitio
    ports:
      - '8081:80'
