version: '3.7'
services:
  Suma:
    container_name: suma
    image: jjauregui1996/suma:latest
    build:
      dockerfile: Dockerfile
      context: ./microservicios/suma
    ports:
      - '8090:8080'

  SumaTest:
    container_name: sumatest
    image: jjauregui1996/sumatest:latest
    build:
      dockerfile: Dockerfile.test
      context: ./microservicios/suma

  SitioWeb:
    container_name: sitioweb
    image: jjauregui1996/sitioweb:latest
    build:
      dockerfile: Dockerfile
      context: ./sitio
    ports:
      - '8081:80'