version: '3.7'
services:
  suma:
    container_name: suma
    build:
      dockerfile: Dockerfile
      context: ./microservicios/suma
    ports:
      - '8090:8080'

  biblioteca:
    container_name: biblioteca
    build:
      dockerfile: Dockerfile
      context: ./microservicios/biblioteca
    ports:
      - '8091:8080'
  
  bibliotecatest:
    container_name: bibliotecatest
    build:
      dockerfile: Dockerfile.test
      context: ./microservicios/biblioteca
      
  cursos:
    container_name: cursos
    build:
      dockerfile: Dockerfile
      context: ./microservicios/cursos
    ports:
      - '8092:8080'
  
  cursotest:
    container_name: cursotest
    build:
      dockerfile: Dockerfile.test
      context: ./microservicios/cursos

  profesores:
    container_name: profesores
    build:
      dockerfile: Dockerfile
      context: ./microservicios/profesores
    ports:
      - '8093:8080'
  
  profesorestest:
    container_name: profesorestest
    build:
      dockerfile: Dockerfile.test
      context: ./microservicios/profesores

  estudiantes:
    container_name: estudiantes
    build:
      dockerfile: Dockerfile
      context: ./microservicios/estudiantes
    ports:
      - '8093:8080'
  
  estudiantestest:
    container_name: estudiantestest
    build:
      dockerfile: Dockerfile.test
      context: ./microservicios/estudiantes
      
  sumatest:
    container_name: sumatest
    build:
      dockerfile: Dockerfile.test
      context: ./microservicios/suma

  sitioweb:
    container_name: sitioweb
    build:
      dockerfile: Dockerfile
      context: ./sitio
    ports:
      - '8081:80'
